name       : perl-test-nowarnings
version    : '1.06'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Test-NoWarnings-1.06.tar.gz : c2dc51143b7eb63231210e27df20d2c8393772e0a333547ec8b7a205ed62f737
homepage   : https://metacpan.org/pod/Test::NoWarnings
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Test::NoWarnings - Make sure you didn't emit any warnings while testing
description: |
    In general, your tests shouldn't produce warnings. This modules causes any warnings to be captured and stored. It automatically adds an extra test that will run when your script ends to check that there were no warnings. If there were any warings, the test will give a "not ok" and diagnostics of where, when and what the warning was, including a stack trace of what was going on when the it occurred.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
