name       : perl-test-nowarnings
version    : 1.04
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/A/AD/ADAMK/Test-NoWarnings-1.04.tar.gz : 638a57658cb119af1fe5b15e73d47c2544dcfef84af0c6b1b2e97f08202b686c
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Test::NoWarnings - Make sure you didn't emit any warnings while testing
description: |
    In general, your tests shouldn't produce warnings. This modules causes any warnings to be captured and stored. It automatically adds an extra test that will run when your script ends to check that there were no warnings. If there were any warings, the test will give a "not ok" and diagnostics of where, when and what the warning was, including a stack trace of what was going on when the it occurred.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
